### PR TITLE
Upload Model File to Rasa X on Merge

### PR DESCRIPTION
**Pull request by b-quachtran**
Updated Github CI workflow to upload the new model file (when applicable) to Rasa X

### CODE REVIEW

**Comment by b-quachtran** [comment]
@melindaloubser1 Not entirely sure what I'm doing, any input would be super helpful

**Comment by melindaloubser1** [comment]
Looks good actually! Did you test it on another repo to see if it runs as expected?

**Review by melindaloubser1 — COMMENTED** [review]
@b-quachtran is this "ready for review" yet? It looks right to me

**Comment by b-quachtran** [comment]
@melindaloubser1 Sorry, I've been meaning to test in a separate repo but haven't quite gotten to it yet. I'll lyk when it's ready for review

**Review by melindaloubser1 — APPROVED** [review]
woot!

**Comment by melindaloubser1** [comment]
haha well I guess the CI says not quite yet.

**Comment by b-quachtran** [comment]
Huh, it's working now? I tried fixing the jitterbit problem on Monday and couldn't figure it out

**Comment by b-quachtran** [comment]
Oh this could still be a problem. Jitterbit will start working when you push an additional commit to the PR because it has something to compare between the base and head commit, but will fail if there are no extra commits

**Comment by b-quachtran** [comment]
I'm going to take a closer look when I get a chance (probably tomorrow)

**Comment by melindaloubser1** [comment]
No worries, jitterbit is like that - I don't think it's an issue with your PR and it passed CI so I merged it =)

**Pull request merged**
