### PR TITLE
Upgrade to 1.7.0 

### PR DESCRIPTION
**Pull request by erohmensing**
Based on the changelog:
- rename templates to resposes
- remove utter actions from action list
- go back to softmax loss type now that normalization is implemented
- reduce ranking length to 5

Don't want to merge this quite yet, will wait until rasa x 0.25 is out and we update the instance

### CODE REVIEW

**Comment by akelad** [comment]
can we get an nlu eval github action like in carbon bot too? :D

**Comment by erohmensing** [comment]
tbh i thought we had one 🤔

**Comment by akelad** [comment]
removing utter actions from the actions list has got to be the best thing ever. 
@btotharye do we have a github action for nlu eval?

**Comment by btotharye** [comment]
sorry never saw this but yea @akelad it has the PR nlu eval, https://github.com/RasaHQ/rasa-demo/blob/master/.github/workflows/build_and_deploy.yml#L83

**Pull request merged**
