### PR TITLE
add mergepal

### LINKED ISSUE #534: Add mergepal to repo
For our sanity! Our CI takes a long time to train as well, might as well add mergepal now that we have it in rasa and rasa x

### PR DESCRIPTION
**Pull request by erohmensing**
- snagged from https://github.com/RasaHQ/rasa/pull/5829/files
- close #534

### CODE REVIEW

**Comment by erohmensing** [comment]
I believe the token here has auth, think we can just approve it, add the tag and see if it works. If we run into issues with this: https://github.com/maxkomarychev/merge-pal-action#note-about-tokens then i'll need a different token

**Comment by melindaloubser1** [comment]
trying it out here https://github.com/RasaHQ/rasa-demo/pull/495

**Comment by melindaloubser1** [comment]
Hey look it worked!!

**Comment by erohmensing** [comment]
Dooope

**Pull request merged**
