### PR TITLE
Replacing Travis with Github Actions

### PR DESCRIPTION
**Pull request by btotharye**

### CODE REVIEW

**Comment by btotharye** [comment]
future PR will also compare the master branch to the PR branch but will take a little longer to add that so wanted to merge it before then.

**Comment by rgstephens** [comment]
Remind me was this the intermittent auth failure you kept running into?

```
Current runner version: '2.163.1'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'actions/gcloud@master'
##[warning]Failed to download action 'https://api.github.com/repos/actions/gcloud/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 19.311 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/gcloud/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 29.987 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

**Comment by btotharye** [comment]
> Remind me was this the intermittent auth failure you kept running into?
> 
> ```
> Current runner version: '2.163.1'
> Prepare workflow directory
> Prepare all required actions
> Download action repository 'actions/checkout@v1'
> Download action repository 'actions/gcloud@master'
> ##[warning]Failed to download action 'https://api.github.com/repos/actions/gcloud/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
> ##[warning]Back off 19.311 seconds before retry.
> ##[warning]Failed to download action 'https://api.github.com/repos/actions/gcloud/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
> ##[warning]Back off 29.987 seconds before retry.
> ##[error]Response status code does not indicate success: 404 (Not Found).
> ```

No this is something different it appears.  Before it wasn't logging in but I resolved that.

**Comment by btotharye** [comment]
yea it appears @rgstephens the original github actions repo I was using for the google cloud auth and such got deprecated and deleted so I'm updating it now with, https://github.com/GoogleCloudPlatform/github-actions.

Will let you know when it's ready.

**Comment by btotharye** [comment]
Ok I have now updated the github actions for the deploy steps to use the updated Google Cloud Platform repo that isn't deprecated :)

**Comment by rgstephens** [comment]
Looks good!

**Comment by erohmensing** [comment]
Woo! don't forget to squash :)

**Comment by btotharye** [comment]
And done 🚀

**Pull request merged**
