### PR TITLE
Changes left from Sara in the orange state

### PR DESCRIPTION
**Pull request by TyDunn**

### CODE REVIEW

**Comment by wochinge** [comment]
Ty, can you describe what changes you did explicitly and which ones were introduced as a side-effect?

**Comment by akelad** [comment]
i don't think ty made any changes, but the person before him seemed to have added "what is RASA X" - the rest just seems to have somehow rearranged itself

**Comment by akelad** [comment]
looks like there's a bunch of random changes here as well: https://github.com/RasaHQ/rasa-demo/pull/457/files

**Comment by TyDunn** [comment]
Yeah, I did not make any changes. They were there when I wanted to annotate and no one remembered making them

**Comment by melindaloubser1** [comment]
@TyDunn can this be closed?

**Pull request closed without merging**
