### PR TITLE
Update intent_description_mapping.csv

### PR DESCRIPTION
**Pull request by kr-prince**
Added "," at line no 41 for correct csv format

### CODE REVIEW

**Review by erohmensing — APPROVED** [review]
cheers, thanks!

**Comment by kr-prince** [comment]
@erohmensing Could you please help to merge this? I am not very well versed in Github.

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @tabergma will take a look at it as soon as possible ✨

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @rgstephens will take a look at it as soon as possible ✨

**Pull request merged**
