### PR TITLE
implement pipeline form

### PR DESCRIPTION
**Pull request by erohmensing**
Pushing @ArjaanBuijk's changes separately since they touch a lot of files

### CODE REVIEW

**Comment by erohmensing** [comment]
oops we really should have done this off of master, @ArjaanBuijk can you handle the merge conflicts?

**Comment by ArjaanBuijk** [comment]
@erohmensing ,
yes,  I will resolve the merge conflicts once PR https://github.com/RasaHQ/rasa-demo/pull/450 is merged.

**Comment by erohmensing** [comment]
@ArjaanBuijk are we moving forward on this?

**Comment by ArjaanBuijk** [comment]
I will close this. The whole pipeline logic has changed, and it is just as easy to start over at this point.

**Pull request closed without merging**
