### PR TITLE
python3 command

### PR DESCRIPTION
**Pull request by johnycage**

### CODE REVIEW

**Comment by johnycage** [comment]
python3 command is needed for latest version. Suggested changes in Makefile.

**Comment by trammell** [comment]
I can't think of any OS or environment that uses python 2.x these days. Is this really a problem?

**Comment by johnycage** [comment]
> I can't think of any OS or environment that uses python 2.x these days. Is this really a problem?

I don't have 'python-is-python3' package installed on my Ubuntu 22.04 and so for any default installation on Ubuntu python3 is goto command. (python i.e. python2 is not installed).
May be a note can be added, so make install can run smoothly.

**Comment by trammell** [comment]
One possible workaround for you would be to create a shell alias, something like

```bash
alias python=/usr/bin/python3.10
```

**Comment by johnycage** [comment]
> One possible workaround for you would be to create a shell alias, something like
> 
> ```shell
> alias python=/usr/bin/python3.10
> ```

That's right, but then we must mention in the setup documentation about python3 caveat. Let's add a line in readme maybe.

**Pull request closed without merging**
